#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: $0 <deb dir>"
  exit 1
fi

dir=$1

reprepro --keepunreferencedfiles includedeb bullseye ${dir}/*-d11_*.deb
reprepro --keepunreferencedfiles includedeb bookworm ${dir}/*-d12_*.deb
reprepro --keepunreferencedfiles includedeb trixie   ${dir}/*-d13_*.deb

